"""
Gazetteer: Curated lookup dictionary for AI publications tag extraction.
Each entry maps a canonical term to its category.
Matching is case-insensitive and supports multi-word terms.
"""

GAZETTEER: dict[str, str] = {

    # AI/ML Terminology
    "transformer": "AI/ML Concept",
    "attention mechanism": "AI/ML Concept",
    "self-attention": "AI/ML Concept",
    "multi-head attention": "AI/ML Concept",
    "large language model": "AI/ML Concept",
    "LLM": "AI/ML Concept",
    "foundation model": "AI/ML Concept",
    "generative AI": "AI/ML Concept",
    "retrieval-augmented generation": "AI/ML Concept",
    "RAG": "AI/ML Concept",
    "fine-tuning": "AI/ML Concept",
    "instruction tuning": "AI/ML Concept",
    "RLHF": "AI/ML Concept",
    "reinforcement learning from human feedback": "AI/ML Concept",
    "prompt engineering": "AI/ML Concept",
    "chain-of-thought": "AI/ML Concept",
    "in-context learning": "AI/ML Concept",
    "few-shot learning": "AI/ML Concept",
    "zero-shot learning": "AI/ML Concept",
    "transfer learning": "AI/ML Concept",
    "diffusion model": "AI/ML Concept",
    "generative adversarial network": "AI/ML Concept",
    "GAN": "AI/ML Concept",
    "variational autoencoder": "AI/ML Concept",
    "VAE": "AI/ML Concept",
    "graph neural network": "AI/ML Concept",
    "GNN": "AI/ML Concept",
    "convolutional neural network": "AI/ML Concept",
    "CNN": "AI/ML Concept",
    "recurrent neural network": "AI/ML Concept",
    "RNN": "AI/ML Concept",
    "LSTM": "AI/ML Concept",
    "BERT": "AI/ML Concept",
    "GPT": "AI/ML Concept",
    "vision transformer": "AI/ML Concept",
    "ViT": "AI/ML Concept",
    "multimodal": "AI/ML Concept",
    "embedding": "AI/ML Concept",
    "vector database": "AI/ML Concept",
    "knowledge graph": "AI/ML Concept",
    "federated learning": "AI/ML Concept",
    "continual learning": "AI/ML Concept",
    "meta-learning": "AI/ML Concept",
    "neural architecture search": "AI/ML Concept",
    "NAS": "AI/ML Concept",
    "quantization": "AI/ML Concept",
    "model compression": "AI/ML Concept",
    "pruning": "AI/ML Concept",
    "distillation": "AI/ML Concept",
    "knowledge distillation": "AI/ML Concept",
    "explainability": "AI/ML Concept",
    "interpretability": "AI/ML Concept",
    "fairness": "AI/ML Concept",
    "AI safety": "AI/ML Concept",
    "alignment": "AI/ML Concept",
    "hallucination": "AI/ML Concept",
    "tokenization": "AI/ML Concept",
    "natural language processing": "AI/ML Concept",
    "NLP": "AI/ML Concept",
    "computer vision": "AI/ML Concept",
    "speech recognition": "AI/ML Concept",
    "object detection": "AI/ML Concept",
    "image segmentation": "AI/ML Concept",
    "named entity recognition": "AI/ML Concept",
    "NER": "AI/ML Concept",
    "sentiment analysis": "AI/ML Concept",
    "question answering": "AI/ML Concept",
    "machine translation": "AI/ML Concept",
    "text summarization": "AI/ML Concept",
    "information retrieval": "AI/ML Concept",
    "reinforcement learning": "AI/ML Concept",
    "deep reinforcement learning": "AI/ML Concept",
    "model evaluation": "AI/ML Concept",
    "benchmark": "AI/ML Concept",
    "dataset": "AI/ML Concept",
    "pretraining": "AI/ML Concept",
    "PEFT": "AI/ML Concept",
    "LoRA": "AI/ML Concept",
    "agent": "AI/ML Concept",
    "agentic AI": "AI/ML Concept",
    "autonomous agent": "AI/ML Concept",
    "tool use": "AI/ML Concept",
    "reasoning": "AI/ML Concept",
    "planning": "AI/ML Concept",
    "mixture of experts": "AI/ML Concept",
    "MoE": "AI/ML Concept",
    "speculative decoding": "AI/ML Concept",
    "inference optimization": "AI/ML Concept",

    # Notable People in AI
    "Geoffrey Hinton": "AI Researcher",
    "Yann LeCun": "AI Researcher",
    "Yoshua Bengio": "AI Researcher",
    "Andrew Ng": "AI Researcher",
    "Ilya Sutskever": "AI Researcher",
    "Sam Altman": "AI Leader",
    "Demis Hassabis": "AI Researcher",
    "Fei-Fei Li": "AI Researcher",
    "Andrej Karpathy": "AI Researcher",
    "Ian Goodfellow": "AI Researcher",
    "Pieter Abbeel": "AI Researcher",
    "Dario Amodei": "AI Leader",
    "Daniela Amodei": "AI Leader",
    "Jeff Dean": "AI Researcher",
    "Samy Bengio": "AI Researcher",
    "Quoc Le": "AI Researcher",
    "Percy Liang": "AI Researcher",
    "Chelsea Finn": "AI Researcher",
    "Alec Radford": "AI Researcher",
    "Stuart Russell": "AI Researcher",
    "Nick Bostrom": "AI Researcher",
    "Turing": "AI Pioneer",
    "Alan Turing": "AI Pioneer",
    "John McCarthy": "AI Pioneer",
    "Marvin Minsky": "AI Pioneer",

    # Organizations & Labs
    "OpenAI": "AI Organization",
    "DeepMind": "AI Organization",
    "Google DeepMind": "AI Organization",
    "Anthropic": "AI Organization",
    "Meta AI": "AI Organization",
    "FAIR": "AI Organization",
    "Google Brain": "AI Organization",
    "Google Research": "AI Organization",
    "Microsoft Research": "AI Organization",
    "IBM Research": "AI Organization",
    "Hugging Face": "AI Organization",
    "EleutherAI": "AI Organization",
    "Stability AI": "AI Organization",
    "Mistral AI": "AI Organization",
    "Cohere": "AI Organization",
    "AI21 Labs": "AI Organization",
    "Together AI": "AI Organization",
    "Nvidia": "AI Organization",
    "Tesla AI": "AI Organization",
    "Apple ML Research": "AI Organization",
    "Amazon AWS AI": "AI Organization",
    "Allen Institute for AI": "AI Organization",
    "AI2": "AI Organization",
    "Vector Institute": "AI Organization",
    "MILA": "AI Organization",
    "Stanford HAI": "AI Organization",
    "MIT CSAIL": "AI Organization",
    "Berkeley AI Research": "AI Organization",
    "BAIR": "AI Organization",
    "CMU AI": "AI Organization",
    "Oxford Future of Humanity Institute": "AI Organization",
    "FHI": "AI Organization",
    "Center for AI Safety": "AI Organization",
    "CAIS": "AI Organization",
    "Partnership on AI": "AI Organization",

    # Conferences & Journals (AI/ML)
    "NeurIPS": "AI Conference",
    "Neural Information Processing Systems": "AI Conference",
    "ICML": "AI Conference",
    "International Conference on Machine Learning": "AI Conference",
    "ICLR": "AI Conference",
    "International Conference on Learning Representations": "AI Conference",
    "CVPR": "AI Conference",
    "ECCV": "AI Conference",
    "ICCV": "AI Conference",
    "ACL": "AI Conference",
    "EMNLP": "AI Conference",
    "NAACL": "AI Conference",
    "AAAI": "AI Conference",
    "IJCAI": "AI Conference",
    "KDD": "AI Conference",
    "WWW": "AI Conference",
    "SIGIR": "AI Conference",
    "JMLR": "AI Journal",
    "Journal of Machine Learning Research": "AI Journal",
    "Transactions on Machine Learning Research": "AI Journal",
    "TMLR": "AI Journal",
    "Nature Machine Intelligence": "AI Journal",
    "IEEE Transactions on Neural Networks": "AI Journal",
    "Artificial Intelligence": "AI Journal",
    "arXiv": "Preprint Server",

    # Healthcare Journals
    "NEJM": "Healthcare Journal",
    "New England Journal of Medicine": "Healthcare Journal",
    "The Lancet": "Healthcare Journal",
    "Lancet Digital Health": "Healthcare Journal",
    "JAMA": "Healthcare Journal",
    "Journal of the American Medical Association": "Healthcare Journal",
    "BMJ": "Healthcare Journal",
    "British Medical Journal": "Healthcare Journal",
    "Nature Medicine": "Healthcare Journal",
    "npj Digital Medicine": "Healthcare Journal",
    "Journal of Medical Internet Research": "Healthcare Journal",
    "JMIR": "Healthcare Journal",
    "Radiology": "Healthcare Journal",
    "Journal of the American Medical Informatics Association": "Healthcare Journal",
    "JAMIA": "Healthcare Journal",
    "Annals of Internal Medicine": "Healthcare Journal",
    "PLOS Medicine": "Healthcare Journal",
    "Cell": "Healthcare Journal",
    "Science Translational Medicine": "Healthcare Journal",
    "EBioMedicine": "Healthcare Journal",

    # AI in Healthcare
    "clinical NLP": "AI+Healthcare",
    "medical imaging": "AI+Healthcare",
    "clinical decision support": "AI+Healthcare",
    "electronic health records": "AI+Healthcare",
    "EHR": "AI+Healthcare",
    "precision medicine": "AI+Healthcare",
    "drug discovery": "AI+Healthcare",
    "genomics": "AI+Healthcare",
    "pathology AI": "AI+Healthcare",
    "radiology AI": "AI+Healthcare",
    "clinical trial": "AI+Healthcare",
    "digital health": "AI+Healthcare",
    "health informatics": "AI+Healthcare",
    "bioinformatics": "AI+Healthcare",
    "medical AI": "AI+Healthcare",
}


def build_lookup_index(gazetteer: dict[str, str]) -> list[tuple[str, str, str]]:
    """
    Build a sorted lookup index from the gazetteer.
    Returns list of (lowercase_term, canonical_term, category) tuples,
    sorted by term length descending so longer phrases match first.
    """
    index = [
        (term.lower(), term, category)
        for term, category in gazetteer.items()
    ]
    index.sort(key=lambda x: len(x[0]), reverse=True)
    return index


# Pre-built index used by the extraction node
GAZETTEER_INDEX = build_lookup_index(GAZETTEER)